//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NTSyslogCtrl.rc
//
#define IDOK2                           3
#define SUGGESTSETTINGS                 3
#define IDM_ABOUTBOX                    0x0010
#define IDC_ABOUTBOX                    0x0010
#define IDC_HELPBOX                     17
#define IDD_ABOUTBOX                    100
#define IDD_NTSYSLOGCTRL_DIALOG         101
#define IDD_SYSTEM_DIALOG               102
#define IDD_APPLICATION_DIALOG          104
#define IDD_SECURITY_DIALOG             105
#define IDS_ABOUTBOX                    107
#define IDD_CONFAPPL                    108
#define IDR_MAINFRAME                   128
#define IDI_GREEN_ICON                  129
#define IDI_YELLOW_ICON                 130
#define IDI_RED_ICON                    131
#define IDI_ERROR_ICON                  132
#define IDC_STATUS_LIGHT                200
#define IDC_STATUS                      201
#define IDC_SELECT_COMPUTER             202
#define IDC_START                       203
#define IDC_STOP                        204
#define IDC_SYSLOGD                     205
#define IDC_APPLICATIONS                206
#define IDC_SECURITY                    207
#define IDC_SYSTEM                      208
#define IDC_COMPUTER                    209
#define IDC_INFORMATION_CHECK           210
#define IDC_WARNING_CHECK               211
#define IDC_PRIMARY_SYSLOGD             212
#define IDC_ERROR_CHECK                 213
#define IDC_BACKUP_SYSLOGD              214
#define IDC_SUCCESS_CHECK               214
#define IDC_DEFAULTS                    215
#define IDC_AUDIT_SUCCESS_CHECK         216
#define IDC_AUDIT_FAILURE_CHECK         217
#define IDC_LABEL                       220
#define IDC_INFO_FACILITY               221
#define IDC_INFO_SEVERITY               222
#define IDC_WARNING_FACILITY            223
#define IDC_EVENTLOG_SELECT             223
#define IDC_WARNING_SEVERITY            224
#define IDC_EVENTLOG                    224
#define IDC_ERROR_FACILITY              225
#define IDC_ERROR_SEVERITY              226
#define IDC_AUDIT_SUCCESS_FACILITY      227
#define IDC_AUDIT_SUCCESS_SEVERITY      228
#define IDC_BUTTON1                     228
#define IDC_INSTALL                     228
#define IDC_BROWSE                      228
#define IDC_AUDIT_FAILURE_FACILITY      229
#define IDC_BROWSE2                     229
#define IDC_AUDIT_FAILURE_SEVERITY      230
#define IDC_IPADDRESS2                  230
#define IDC_BROWSE_ROTATE1              230
#define IDC_BROWSE_ROTATE2              231
#define IDC_SUCCESS_FACILITY            231
#define IDC_USEPING                     232
#define IDC_INFO_SEVERITY2              232
#define IDC_SUCCESS_SEVERITY            232
#define IDC_PORT                        233
#define IDC_FORWARD_EVENTS              234
#define IDC_EDIT_APPLICATION            235
#define IDC_PORT2                       236
#define IDC_APPLICATION_LIST            237
#define IDC_FORWARD_APPLICATION         238
#define IDC_ADD_APPLICATION             239
#define IDC_STATIC_CURR_APPL            240
#define IDC_APPNAME                     241
#define IDC_FTPUSER                     241
#define IDC_FORWARD_EVENTS2             241
#define IDC_USE_MIRROR                  241
#define IDC_APP_PATH                    242
#define IDC_FTPPASS                     242
#define IDC_FILE_EXT                    243
#define IDC_DIRECTORY                   243
#define IDC_PARSE_DATE                  244
#define IDC_DEL_LOG_FILES               244
#define IDC_PARSE_HOST                  245
#define IDC_PARSE_PROCESS               246
#define IDC_APP_FILEPATH                247
#define IDC_RAW_MODE                    248
#define IDC_PARSE_DATE2                 248
#define IDC_UNICODE                     248
#define IDC_COMBOBOXEX1                 250
#define IDC_FACILITY                    250
#define IDC_COMBOBOXEX2                 251
#define IDC_CHECK6                      252
#define IDC_USE_PREFIX                  252
#define IDC_PREFIX                      253
#define IDC_USE_IGNORE_LINES            254
#define IDC_LINES_TO_IGNORE             255
#define IDC_PROCESS_NAME                256
#define IDC_PARSE_SEVERITY              257
#define IDC_REMOVEAPPLICATION           258
#define IDC_SEVERITY_LEVEL              263
#define IDC_COMBO1                      264
#define IDC_RADIO_FILE                  265
#define IDC_RADIO_DIR                   266
#define IDC_RADIO_ROTATE_FILE           267
#define IDC_APP_ROTATE_FILE1            268
#define IDC_APP_ROTATE_FILE2            269
#define IDC_HELP2                       271
#define IDC_DIR                         272
#define IDC_EDIT1                       272
#define IDC_FILTERARRAY                 272
#define IDC_RADIO_UDP                   273
#define IDC_RADIO_UDP_PING              274
#define IDC_RADIO_TCP                   275
#define IDD_CONFIG_LOG                  301
#define IDS_APPLICATION_LOG_TITLE       57345
#define IDS_APPLICATION_LOG_PATH        57346
#define IDS_SECURITY_LOG_TITLE          57347
#define IDS_SECURITY_LOG_PATH           57348
#define IDS_SYSTEM_LOG_TITLE            57349
#define IDS_SYSTEM_LOG_PATH             57350
#define IDS_CONFIRM_SAVE                57351
#define IDS_CONFIRM_DISCARD             57352

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        310
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         276
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
